name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      - name: Export CHROME_BIN Env Variable
        run: export CHROME_BIN=chromium-browser

      - name: Export Display Variable
        run: export DISPLAY=:99.0

      - name: Install Ruby
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          ruby-version: 2.7.8

      - name: Install Dependencies
        run: npm install

      - name: Bundle Install
        run: bundle install

      - name: Install Firefox
        uses: browser-actions/setup-firefox@0bc507ddf224827e3b1af68e014d5e42ab93e795 # v1.7.2

      - name: Run Gulp
        uses: GabrielBB/xvfb-action@86d97bde4a65fe9b290c0b3fb92c2c4ed0e5302d # v1.6
        with:
          run: gulp default --ci

      - name: Run Code Coverage
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
