name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Export CHROME_BIN Env Variable
        run: export CHROME_BIN=chromium-browser

      - name: Export Display Variable
        run: export DISPLAY=:99.0

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Install Dependencies
        run: npm install

      - name: Bundle Install
        run: bundle install

      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Run Gulp
        uses: GabrielBB/xvfb-action@v1
        with:
          run: gulp default --ci

      - name: Run Code Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
