name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Export CHROME_BIN Env Variable
        run: export CHROME_BIN=chromium-browser

      - name: Export Display Variable
        run: export DISPLAY=:99.0

      - name: Install Ruby
        uses: ruby/setup-ruby@9669f3ee51dc3f4eda8447ab696b3ab19a90d14b
        with:
          ruby-version: 2.7.3

      - name: Install Dependencies
        run: npm install

      - name: Bundle Install
        run: bundle install

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y firefox xvfb

      - name: Run Gulp
        uses: GabrielBB/xvfb-action@v1
        with:
          run: gulp default --ci
